[tool.mypy]
exclude = "tests"
html_report = "reports/mypy"
xml_report = "reports/mypy"
junit_xml = "reports/mypy/mypy-junit.xml"
pretty = true
strict = true

[tool.coverage.run]
# Medir cobertura de ramas
branch = true
source = [
    # Incluir todo automáticamente
    ".",
]

# Especifica archivos o directorios para excluir de la cobertura
omit = [
    "tests/*",
    "venv/*",
    ".venv/*",
]

[tool.coverage.html]
directory = "reports/coverage"

[tool.coverage.xml]
output = "reports/coverage/coverage.xml"

[tool.pytest.ini_options]
addopts = "--html=reports/tests/pytest.html --cov=./ --cov-report=term --cov-report=html --cov-report=xml --junit-xml=reports/tests/pytest.xml"

[tool.ruff.lint]
select = [
    "ALL",
    "D212", # multi-line docstring summary in first line
]

[tool.ruff.lint.per-file-ignores]
# ignores for tests, expanded from https://github.com/astral-sh/ruff/issues/4368
"tests/**/*.py" = [
    "S101", # asserts allowed in tests...
    "ARG", # Unused function args -> fixtures nevertheless are functionally relevant...
    "FBT", # Don't care about booleans as positional arguments in tests, e.g. via @pytest.mark.parametrize()
    "PLR2004", # Magic value used in comparison
    "S311", # Standard pseudo-random generators are not suitable for cryptographic purposes
    "ANN", # Don't check missing annotations
    "D", # Missing docstrings
]

[tool.ruff.lint.pydocstyle]
convention = "pep257"
