[lint]
select = [
    "ALL",
    "D212", # multi-line docstring summary in first line
]

[lint.pydocstyle]
convention = "pep257"

[lint.per-file-ignores]
# ignores for tests, expanded from https://github.com/astral-sh/ruff/issues/4368
"tests/**/*.py" = [
    "S101", # asserts allowed in tests...
    "ARG", # Unused function args -> fixtures nevertheless are functionally relevant...
    "FBT", # Don't care about booleans as positional arguments in tests, e.g. via @pytest.mark.parametrize()
    "PLR2004", # Magic value used in comparison
    "S311", # Standard pseudo-random generators are not suitable for cryptographic purposes
    "ANN", # Don't check missing annotations
    "D", # Missing docstrings
]
