# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
    paths:
      # run if code, tests, dependencies and/or settings are changed
      - '**.py'
      - 'tests/**'
      - 'requirements*.txt'
      - 'pytest.ini'
      - '.coveragerc'
      # of course, run if this workflow itself is changed
      - '.github/workflows/ci.yml'
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        mkdir -p reports/flake8
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --output-file reports/flake8/flake8stats.txt --format=html --htmldir=reports/flake8
    - name: Test with pytest
      run: |
        pytest
    - name: Update reports and generate badges
      if: always()
      run: |
        # generate badges for flake8, coverage and tests
        genbadge flake8 -o reports/flake8/badge.svg
        genbadge coverage -o reports/coverage/badge.svg
        genbadge tests -i reports/tests/pytest.xml -o reports/tests/badge.svg

        # prepare commit
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        # force adding everything
        git add -f reports
        git commit -m 'CI: update reports and badges'
        git push
