# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    paths:
      # run if code, tests, dependencies and/or settings are changed
      - '**.py'
      - 'tests/**'
      - 'requirements*.txt'
      - 'pytest.ini'
      - '.coveragerc'
      # of course, run if this workflow itself is changed
      - '.github/workflows/ci.yml'
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Extract branch name
      run: echo "BRANCH_NAME=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_ENV
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        mkdir -p reports/flake8
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --output-file reports/flake8/flake8stats.txt --format=html --htmldir=reports/flake8
    - name: Lint with Ruff
      run: |
        ruff check --exit-zero --output-format github
    - name: Test with pytest
      run: |
        pytest
    - name: Update reports and generate badges
      if: always()
      run: |
        # generate badges for flake8, coverage and tests
        genbadge flake8 -o reports/flake8/badge.svg
        genbadge coverage -o reports/coverage/badge.svg
        genbadge tests -i reports/tests/pytest.xml -o reports/tests/badge.svg
        mkdir ${BRANCH_NAME}
        mv reports/* ${BRANCH_NAME}
        mv ${BRANCH_NAME} reports
    - name: Upload reports as artifact
      if: always()
      uses: actions/upload-pages-artifact@v3
      with:
        path: reports

  deploy-reports:
    # Add a dependency to the build job
    needs: build

    # Run even if build fails
    if: always()

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
