# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: build

on:
  push:
    paths:
      # run if code, tests, dependencies, settings and/or reports are changed
      - '**.py'
      - 'tests/**'
      - 'requirements*.txt'
      - 'pyproject.toml'
      - 'pytest.ini'
      - '.coveragerc'
      - 'report-templates/**'
      # of course, run if this workflow itself is changed
      - '.github/workflows/ci.yml'
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Extract branch name
      run: echo "BRANCH_NAME=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_ENV
    - name: List installed packages
      run: apt list --installed
    - name: Who am I?
      run: |
        echo Current user: $(id -u):$(whoami)
        sudo su -c 'echo sudo user: $(id -u):$(whoami)'
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        mkdir -p reports/flake8
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --output-file reports/flake8/flake8stats.txt --format=html --htmldir=reports/flake8
    - name: Lint with Ruff
      run: |
        ruff check --exit-zero --output-format github
    - name: Check typing with mypy
      run: |
        mypy . || true
    - name: Test with pytest
      run: |
        pytest
    - name: Upload coverage to coveralls.io
      if: always()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        coveralls
    - name: Update reports and generate badges
      if: always()
      run: |
        # generate badges for flake8, coverage and tests
        genbadge flake8 -o reports/flake8/badge.svg
        genbadge coverage -o reports/coverage/badge.svg
        genbadge tests -i reports/tests/pytest.xml -o reports/tests/badge.svg
        # don't ignore any report
        find reports -type f -name '.gitignore' -delete
        # put reports in branch folder for gh-pages
        mkdir ${BRANCH_NAME}
        mv reports/* ${BRANCH_NAME}
        mv ${BRANCH_NAME} reports
        cp -a report-templates/* reports
    - name: Try Selenium
      if: always()
      run: |
        python ./try-selenium.py
    - name: Deploy reports to gh-pages
      if: always() && github.event_name == 'push'
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./reports
        keep_files: true
